GCC = gcc
CFLAGS = -g -Wall -Wshadow -Werror -O3 
LIBS = -lm
SOURCES = packing.c 
TARGET = proj3

build: $(TARGET) 

all:
	gcc -Werror -Wbad-function-cast -Wall -Wshadow -O3 packing.c -o proj3

$(TARGET): $(OBJS) | environment 
	$(GCC) $(CFLAGS) -o 
