GCC = gcc
CFLAGS = -g -Werror -Wbad-function-cast -Wall -Wshadow -Werror -O3 
LIBS = -lm
SOURCES = river.c 
TARGET = proj5

build: $(TARGET) 

all:
	gcc -Werror -Wbad-function-cast -Wall -Wshadow -O3 river.c -o proj5

$(TARGET): $(OBJS) | environment 
	$(GCC) $(CFLAGS) -o 
